### ISSUE TITLE
OCCTProxy building errors(AIS_InteractiveContext, AIS_SelectionScheme_XOR)

### ISSUE THREAD

**Issue by artemishenkov** [Open-Cascade-SAS/OCCT-samples-csharp#1]
Hello, when I am trying to build OCCTProxy, I get these errors:
1) Error C2065 'AIS_SelectionScheme_XOR': undeclared identifier OCCTProxy
2) Error C2039 'SelectDetected': is not a member of 'AIS_InteractiveContext' OCCTProxy
3) Error C2039 'SelectRectangle': is not a member of 'AIS_InteractiveContext' OCCTProxy

**Comment by gkv311** [comment]
Hello Artem.

The sample in this repository has been pushed for a development snapshot of OCCT 7.6.0dev, while your errors indicate that you are using some older OCCT version.

So you may:
- Build sample with OCCT 7.6.0dev development snapshot (just clone OCCT master branch);
- [Backport sample](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=commitdiff;h=75cf82505b83f6c85f43b1327e13bd5b88355ff5#patch7) to older OCCT API (e.g. use methods `Select()` and `ShiftSelect()`);
- Build the sample coming with OCCT itself (`samples/CSharp` within OCCT).

**Comment by artemishenkov** [comment]
Thanks, that works for me!
