### ISSUE TITLE
Error cannot open file 'TKIGES.lib'

### ISSUE THREAD

**Issue by Donzasto** [Open-Cascade-SAS/OCCT-samples-csharp#10]
Hello, I built OCCT from sources.
 I added path of the .lib files( TKernel.lib, TKMath.lib ) to OCCTProxy project, but I can't find TKIGES.lib, TKSTEP.lib, TKStl.lib and TKVrml.lib.

**Comment by dpasukhi** [comment]
Hello, the project is archived.
Please check the latest version on:
https://github.com/Open-Cascade-SAS/OCCT/tree/master/samples/CSharp
_
Additionally, You trying to build sample on the latest OCCT, when that repository rely on old version.
