### ISSUE TITLE
Build and run C# sample but not find OCCTProxy.dll 

### ISSUE THREAD

**Issue by rubio1497** [Open-Cascade-SAS/OCCT-samples-csharp#4]
Hi, 
I am trying to build and run the C# sample code, but it can't find the OCCTProxy.dll. I have setting lib / inc to Linker and C/C++ -> gernal. But it's still not working. I am using VS 2019 in Win 10.
Thanks.

![OCCTProxy](https://user-images.githubusercontent.com/44165679/128320079-78aedfc7-33ad-4d1a-b1ad-4995d3fbd551.jpg)

**Comment by gkv311** [comment]
How you are starting the sample? And which one?
Using `run.bat` or from Visual Studio?
In case of Visual Studio - have you specified correct parameters to `msvc.bat` ?

**Comment by rubio1497** [comment]
Hi,
the sample I start is CSharp.sln.  And I start it from Csharp.sln, then it can't run ( can't find OCCTProxy.dll ). But if I start from msvc.bat , it can run (I have specified correct parameters in custom.bat).

**Comment by gkv311** [comment]
> But if I start from msvc.bat , it can run

This is expected behavior. For production deployment you have to copy all necessary dependencies - e.g. OCCT libraries and their nested dependencies (FreeType, FreeImage, etc.) and filter out unused toolkits (to optimuze package size).
