### ISSUE TITLE
gp_Line object

### ISSUE THREAD

**Issue by artemishenkov** [Open-Cascade-SAS/OCCT-samples-csharp#5]
Hello, I'm trying to create a library for reading the .step files and converting their geometry to .dxf format. I've started from lines, but I can't calculate first and last point(**I've found a link on forum but I can't open it: http://www.opencascade.org/org/forum/thread_20239/**). This is how I read files:
STEPControl_Reader reader;
	reader.ReadFile(ToAsciiString(file).ToCString());
	Standard_Integer roots = reader.NbRootsForTransfer();
	Standard_Integer trans = reader.TransferRoots();
	TopoDS_Shape shape = reader.OneShape();
	TopTools_IndexedMapOfShape edges;
	BRepTools::Map3DEdges(shape, edges);

	for (int i = 1; i <  edges.Size(); i++) {
		TopoDS_Edge edge = TopoDS::Edge(edges(i));
		BRepAdaptor_Curve curve(edge);
               if(curve.GetType() == GeomAbs_Line){
                     //  curve.Line().Location().Coord() - first point
                     // ...... - second point?
               }
		
	}
I'd appreciate all the help I can get. Thanks.

**Comment by gkv311** [comment]
It is better asking such questions on the [Forum](https://dev.opencascade.org/forums).

**Comment by artemishenkov** [comment]
Thanks, I'll try.
