### ISSUE TITLE
C# - WPF Sample Build Error

### ISSUE THREAD

**Issue by omerkocabas** [Open-Cascade-SAS/OCCT-samples-csharp#6]
Hi,

To be able to build the sample code, I added OpenCascade headers as additional include directories to OCCTProxy project like in attached photo 1.
![1](https://user-images.githubusercontent.com/58297277/163561925-829c37cb-421d-4115-94a9-ff40c83da7c1.PNG)

Afterwards, I added path of the opencascade .lib files to OCCTProxy project as additional library directories like in attached photo 2 .
![2](https://user-images.githubusercontent.com/58297277/163561949-f2d1536f-5de6-4edc-b144-34b66d444b08.PNG)

Finally, I added all .lib files path as additional dependencies to OCCTProxy project like in attached photo 3.
![3](https://user-images.githubusercontent.com/58297277/163561961-cded8e1e-01b4-484f-b88f-5102ac401e24.PNG)

After these steps I run the "msvc.bat vc142 win64 Debug " command and OCCTProxy.dll has been created successfully. Afterwards WPF project has been built successfully and program is executed. However, when I click new button attached exception occurs. Do you have any idea about this problem? (Attached photo crash)

System.IO.FileNotFoundException: 'Could not load file or assembly 'OCCTProxy.dll' or one of its dependencies. The specified module could not be found.
![Crashh](https://user-images.githubusercontent.com/58297277/163561980-5d33ea4e-4315-4c49-9b5a-c8d90a411ce3.PNG)

Thank you in advance.

**Comment by gkv311** [comment]
`OCCTProxy.dll` loading issues normally indicate missing native DLL dependencies in running environment - like OCCT libraries, or `FreeType.dll`, `FreeImage.dll` and others. This libraries should be either copied into executable folder or put into `%PATH%` variable.

When running native executables, Windows error message is verbose enough and says not just "application cannot be run", but also includes details like dependent DLL that cannot be loaded (with some exceptions).

In contrary, .NET native library loader is very vague, and tells only that directly loaded DLL cannot be loaded for "some reason". As far as I know, there is no other way to trace root cause in .NET environment, so that the most simplest way is to manually check environment or use tools like Depends or [CheckDLL](https://github.com/gkv311/checkdll/releases) to trace dependencies of native libraries.

**Comment by omerkocabas** [comment]
Thank you for response. After several days I was able to fix the issue, I explain for the people who might encounter this again.

As .lib files, including only necessary lib files to the linker is enough.

![image](https://user-images.githubusercontent.com/58297277/164403067-48f011bf-b792-4255-a6e3-ddaebd1cd57d.png)

And the list of missing dlls are stated below.

![image](https://user-images.githubusercontent.com/58297277/164403257-1ae82bdb-c859-4aa0-8568-a87cc7583280.png)

And finally OCCT dlls must be in the same folder with .exe.

![image](https://user-images.githubusercontent.com/58297277/164403677-ce3bff22-a532-46e7-abdf-d76fc15310f4.png)

**Comment by Freydy** [comment]
Hi,

I have the same issue, I tried the solution you posted but I can't get the solution.

This is the configuration I have set:

- Include and library directories:
![image](https://user-images.githubusercontent.com/79274795/166118605-649d85c5-4ad4-4530-9aeb-030311f03ffd.png)

- Linker library directories:
![image](https://user-images.githubusercontent.com/79274795/166118638-34af8f53-cdda-4e2f-a76d-3edd41ec4e10.png)

- Linker:
![image](https://user-images.githubusercontent.com/79274795/166118669-0c3e5251-296d-46d5-b86a-d302295685d8.png)

- OCCS DLLs pasted in the .exe folder:
![image](https://user-images.githubusercontent.com/79274795/166118912-e0ce29ad-f1cd-4cd6-b619-56bc50d3858a.png)

About the missing DLLs what should I do with them? I just pasted in the same folder as the .exe but Idk if this was its place.

Thanks in advanced.

**Comment by omerkocabas** [comment]
Hi, yes missing dlls and OCCT dlls must be in the same folder with .exe. Did u build C++/Cli project with x64 build?

Also you have to add reference from your startup project to C++/Cli project.

**Comment by JoseGR-C** [comment]
Hi. 
I've include all the directories and dll. My problem is 
![image](https://github.com/Open-Cascade-SAS/OCCT-samples-csharp/assets/71220337/f4bac0b5-7721-4391-886a-720b8c1c642d)

I've tried changing the Platform target as the read.me 
![image](https://github.com/Open-Cascade-SAS/OCCT-samples-csharp/assets/71220337/e25195a7-2cb5-4033-aa2c-6f092bf6b529)

But in that case my problem is 
![image](https://github.com/Open-Cascade-SAS/OCCT-samples-csharp/assets/71220337/b102d252-290f-4a66-aac1-712fbb9e873c)
