### ISSUE TITLE
App crashes at opening

### ISSUE THREAD

**Issue by batuhancengiz** [Open-Cascade-SAS/OCCT-samples-csharp#7]
Hello people,

I have successfully built this project and after build I can open exe file and import step etc., however when I copy the executable folder to another windows pc, app crashes, when I click to create document button. I think the problem is about the OCCTProxy.dll and its dependencies. And maybe you know which programs I have to install before run the application. Thanks in advance.

(And I installed C++ Redistributable, just for your information)

![image](https://user-images.githubusercontent.com/82826094/200754957-0831f4e9-9e99-44e4-9262-a8a27c737919.png)

**Comment by gkv311** [comment]
For production deployment you have to copy all necessary dependencies - e.g. OCCT libraries and their nested dependencies (FreeType, FreeImage, etc.). Which libraries to copy depends on your development environment.

Tools like Dependency walker or [checkdll](https://github.com/gkv311/checkdll/releases) could be helpful to trace missing DLLs, but beware that these tools work only on native libraries, not C# modules.
