### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by svedev0** [Open-Cascade-SAS/OCCT-samples-csharp#9]
The link "http://www.opencascade.org/support/products/advsamples" on line 30 of ReadMe.md is dead. It leads to an error page saying "Page not found".

**Comment by dpasukhi** [comment]
Hello, the repository is achieved.
Please check the actual sample folder:
https://github.com/Open-Cascade-SAS/OCCT/tree/master/samples/CSharp
